version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - ls
      # - add-apt-repository -y ppa:deadsnakes/ppa
      # - add-apt-repository -y ppa:ubuntu-toolchain-r/test
      # - apt-get update
      # - apt-get install -y software-properties-common libz3-dev
      # - apt-get install -y libfmt-dev libgmp3-dev libboost-all-dev gcc-11 g++-11
      # - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
      # - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
      # - curl -sSL https://install.python-poetry.org | python -
  build:
    commands:
      - ls
      # - export PATH="/root/.local/bin:$PATH"
      # - poetry run make test_semantics