
version: 0.2

phases:
  pre_build:
    commands:
      - apt update
      - apt install -y software-properties-common
      - add-apt-repository -y ppa:deadsnakes/ppa
      - apt update
      - add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - apt install -y python3.7-dev python3.7 python3.7-venv libfmt-dev libz3-dev libgmp3-dev libboost-all-dev build-essential gcc-11 g++-11 libcvc4-dev
      - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 11
      - update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 11
      - curl -sSL https://install.python-poetry.org | python3.7 -
  build:
    commands:
      - export PATH="/root/.local/bin:$PATH"
      - poetry run make test_semantics
  post_build:
    commands:
      - echo Build completed on `date`
