#!/bin/bash

set -e

dir=tests/behaviour

if [[ ! -d $dir/solidity/ ]]; then
  # Get solidity semantic tests
  git clone --no-checkout --depth=1 https://github.com/ethereum/solidity.git $dir/solidity
fi

pushd $dir/solidity
git config core.sparseCheckout true
echo "test/libsolidity/semanticTests" > .git/info/sparse-checkout
git checkout develop
popd

######### TODO get a version of isoltest for each platform and generate
######### test_calldata.ts instead of having it checked in
# # Generate calldata
# case "$(uname -s)" in
#   Darwin*)
#     isoltest=$dir/bin/darwin/isoltest
#     ;;
#   Linux*)
#     isoltest=$dir/bin/linux/isoltest
#     ;;
# esac

# # Typescript was not resolving the type of the calldata json
# # generated by isoltest nore was it enjoying the empty stub
# # that was used as a placeholder. This way ts properly understands
# # the type of the data.
# cat > $dir/test_calldata.ts <<- EOM
# import { ITestCalldata } from './expectations/semantic';

# const tests : {[file: string]: ITestCalldata[] | null} =
# EOM
# $isoltest --print-test-expectations \
#   --testpath $dir/solidity/test/libsolidity/semanticTests/ \
#   >> $dir/test_calldata.ts
# cat >> $dir/test_calldata.ts <<- EOM
# export default tests;
# EOM
