#!/usr/bin/env python

import platform
import subprocess
import sys
from pathlib import PurePath
from typing import Optional

import pkg_resources


def get_kudu_suffix(system: str) -> Optional[str]:
    system = system.lower()
    if system == "linux":
        return "bin/linux/kudu"
    elif system == "darwin":
        version = platform.mac_ver()[0]
        major, minor = map(int, version.split(".")[:2])
        if major >= 11:
            return "bin/macos/11/kudu"
        elif (major, minor) == (10, 14):
            return "bin/macos/10/14/kudu"
        elif (major, minor) == (10, 15):
            return "bin/macos/10/kudu"


def main(argv):
    suffix = get_kudu_suffix(platform.system())
    if not suffix:
        raise RuntimeError(f"Unsupported OS: {platform.platform()}")
    warp_location = PurePath(pkg_resources.get_distribution("sol-warp").location)
    kudu_location = warp_location / suffix
    res = subprocess.run(
        [kudu_location, *argv[1:]], stdout=sys.stdout, stderr=sys.stderr
    )
    sys.exit(res.returncode)


if __name__ == "__main__":
    main(sys.argv)
