import { execSync } from 'child_process';
import { existsSync, readFileSync, writeFileSync } from 'fs-extra';

let version = '0.8.14';
const filter = process.env.FILTER;

if (filter) {
  console.log(`Using filter for Semantics tests: ${filter}`);
}

if (process.env.VERSION) {
  version = process.env.VERSION;
} else {
  console.warn('No solc version provided for semantic tests, using default: ' + version);
}

if (!existsSync('./tests/behaviour/solidity')) {
  if (!existsSync('./tests/behaviour/setup.sh')) {
    new Error('setup.sh not found');
  }
  execSync(`VERSION=${version}./tests/behaviour/setup.sh`);
}

const whitelistPath = './tests/behaviour/expectations/semantic_whitelist.ts';
const whitelistData = readFileSync(whitelistPath, 'utf-8');

const testsSupportStatus: Map<string, string> = new Map();

whitelistData.split('\n').forEach((line) => {
  const trimmed = line.trim();
  if (trimmed.startsWith(`// 'tests/behaviour/solidity/test/libsolidity/semanticTests/`)) {
    const testPath = trimmed.slice(`// '`.length).trim();
    const testPathLets = testPath.split('//');
    if (testPathLets.length > 1) {
      testsSupportStatus.set(
        testPathLets[0].replace("',", '').trim(),
        testPathLets.slice(1).join('//').trim(),
      );
    } else {
      testsSupportStatus.set(testPathLets[0].replace("',", '').trim(), 'SUPPORTED');
    }
  }
});

// Comparisions of tests between white_list and current version

if (process.argv.includes('--compare')) {
  const testFiles = execSync(
    'find ./tests/behaviour/solidity/test/libsolidity/semanticTests -type f -name "*.sol"',
  )
    .toString()
    .trim()
    .split('\n')
    .sort()
    .filter((file) => {
      if (filter) {
        return file.includes(filter);
      }
      return true;
    })
    .map((file) => file.slice(2));

  console.log(
    `-------Tests which are present in solc version:${version} but not in whitelist------`,
  );
  testFiles.forEach((file) => {
    if (!testsSupportStatus.has(file)) {
      console.log(file);
    }
  });

  console.log(
    `-------Tests which are present in whitelist but not in solc version:${version}------`,
  );
  testsSupportStatus.forEach((value, key) => {
    if (!testFiles.includes(key)) {
      console.log(key);
    }
  });
}

// Test Execution Loop

const testDirs = execSync(
  'find ./tests/behaviour/solidity/test/libsolidity/semanticTests -mindepth 1 -type d',
)
  .toString()
  .trim()
  .split('\n')
  .sort()
  .map((file) => file.slice(2));

const filterDirs: string[] = [
  ...testDirs,
  'tests/behaviour/solidity/test/libsolidity/semanticTests',
];

const currentTestsFileBody = readFileSync(
  './tests/behaviour/expectations/semantic_tests_generated.ts',
  'utf-8',
);

filterDirs.forEach((dir) => {
  const testFiles = execSync(`find ./${dir} -mindepth 1 -maxdepth 1 -name '*.sol'`)
    .toString()
    .trim()
    .split('\n')
    .sort()
    .map((file) => file.slice(2))
    .filter((file) => {
      // ASK: what if there is new test added in the release
      // ASK: i.e test present in this release but not in semantic_whitelist
      //   if (testsSupportStatus.has(file)) {
      //     return testsSupportStatus.get(file) === 'SUPPORTED';
      //   }
      if (filter) {
        return file.includes(filter) && testsSupportStatus.get(file) === 'SUPPORTED';
      }
      return testsSupportStatus.get(file) === 'SUPPORTED';
    });
  if (testFiles.length > 0) {
    console.log(
      `-----------------------------------Running tests from ${dir
        .split('/')
        .pop()}-----------------------------------`,
    );
    const testsFileBody = [
      '// AUTO-GENERATED by semanticTestRunner.ts',
      'const tests:string[] = [',
      ...testFiles.map((file) => {
        return `    "${file}",`;
      }),
      '];',
      'export default tests;',
    ];
    writeFileSync(
      './tests/behaviour/expectations/semantic_tests_generated.ts',
      testsFileBody.join('\n'),
    );
    try {
      execSync(
        `FILTER=${dir} npx mocha tests/behaviour/behaviour.test.ts --extension ts --require ts-node/register --exit`,
        { stdio: 'inherit' },
      );
    } catch (e) {
      console.log(e);
    }
  }
});

writeFileSync('./tests/behaviour/expectations/semantic_tests_generated.ts', currentTestsFileBody);
