name: Github Event Review State

permissions:
  pull-requests: write


on:
  push:
  pull_request_review:
    types: [submitted]

    
jobs:
  run_codebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: echo ${{ github.event.review.state }}