name: Manually Trigger AWS CodeBuild

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: 'Pull request you'd like to build'
        required: false
        type: string
        default: 'latest'

jobs:
  build-dockers:
    if: github.repository_owner == 'NethermindEth'
    runs-on: ubuntu-latest
    steps:
      - name: Echo PR
        run: |
          echo $PULL_REQUEST