name: Manually Trigger AWS CodeBuild

on:
  workflow_dispatch:
    inputs:
      yeet:
        description: 'Pull request you'd like to build'
        required: true
        default: 'latest'

jobs:
  check_variable:
    steps:
      - name: check variable
        if: github.event.inputs.yeet == 'latest'
        run: echo 'PR is latest'