name: Manually Trigger AWS CodeBuild

on: 
  push:
    branches:
      - 'manual_codebuild'
  # workflow_dispatch:
  #   inputs:
  #     pull_request_number:
  #       description: Pull request you'd like to build
  #       required: true
  #       default: latest

jobs:
  check_variables:
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - run: echo "Your PR is ${PR}"
        env:
          PR: ${{ steps.findPr.outputs.pr }}