name: Publish Package to npmjs
on:
  # release:
  #   types: [created]
  push:
    branches:
      - auto-release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-ve3rsion: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: FILTER=anonymous_parameters/func_override yarn test:behaviour
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_RELEASE_KEY }}
