// AUTO-GENERATED by semanticTestRunner.ts
const tests: string[] = [
  'tests/behaviour/solidity/test/libsolidity/semanticTests/accessor/accessor_for_const_state_variable.sol',
  'tests/behaviour/solidity/test/libsolidity/semanticTests/accessor/accessor_for_state_variable.sol',
];
export default tests;
